# Assignment numpy

In [1]:
import numpy as np
# 2-dim array multiplication
a = np.array([(1, 2, 3),(1, 1, 1)])
b = np.array([(1, 1), (1, 3), (2, 4)])

c = np.dot(a, b)
c

array([[ 9, 19],
       [ 4,  8]])

In [14]:
# 3-dim array
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,1,3]]])
e = np.array([[[0,1],[2,3],[1,1]],[[2,7],[5,1],[3,6]]])
print(d.dtype)
print(d.shape)
print(d)
print(e.dtype)
print(e.shape)
print(e)

int32
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 1 3]]]
int32
(2, 3, 2)
[[[0 1]
  [2 3]
  [1 1]]

 [[2 7]
  [5 1]
  [3 6]]]


In [15]:
# 3-dim array multiplication
np.dot(d, e)

array([[[[  7,  10],
         [ 21,  27]],

        [[ 16,  25],
         [ 51,  69]]],


       [[[ 25,  40],
         [ 81, 111]],

        [[  5,   7],
         [ 16,  26]]]])

In [17]:
# using sin and cos
angle1 = 30
angle2 = 60
x = np.sin(angle1)
y = np.cos(angle2)
z = x * y
print(z)

0.9410141438467099


In [22]:
# tan of angles
q = np.tan(angle1)
r = np.tan(angle2)
print(q)
print(r)

-6.405331196646276
0.320040389379563


In [23]:
# using log
np.log(r)

-1.139308074341902

In [36]:
# using matmul to multiply 5x3 matrix
p = [[1,2,9],
    [3,2,1],
    [4,5,2],
    [1,9,3],
    [6,2,4]]
j = [[1,1,2,2,3],
     [2,4,5,1,2],
     [6,4,3,2,6]]
np.matmul(p, j)



array([[59, 45, 39, 22, 61],
       [13, 15, 19, 10, 19],
       [26, 32, 39, 17, 34],
       [37, 49, 56, 17, 39],
       [34, 30, 34, 22, 46]])

In [37]:
# creating a 3x3 identity matrix
imatrix = np.eye(3)

In [38]:
imatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# creating a 3x3 random matrix with integer between 2 and 10
np.random.randint(2,10, size=(3,3))

array([[2, 3, 4],
       [5, 8, 7],
       [4, 8, 9]])

In [63]:
# inverse of a matrix
n = np.array([[1,1],[2,1]])

t = np.linalg.inv(n)
t

array([[-1.,  1.],
       [ 2., -1.]])

In [76]:
# changing the shape of a matrix e.g 3x2 into 2x3
w = np.array([[1,3,5,9],[1,1,1,0],[3,1,7,5]])
print(w)
w.reshape(4,3)

[[1 3 5 9]
 [1 1 1 0]
 [3 1 7 5]]


array([[1, 3, 5],
       [9, 1, 1],
       [1, 0, 3],
       [1, 7, 5]])